name: ElChat
main: jp.commun.minecraft.elchat.ElChatPlugin
version: ${project.version}
description: Flexible Channel Chat
author: ayunyan
website: http://minecraft.commun.jp/
softdepends: [ PermissionsEx, dynmap ]
commands:
    elchat:
        description: ElChat Command
    irc:
        description: IRC Command
    channel:
        description: Channel Command
    ch:
        description: Channel Command
    join:
        description: Channel Join Command
    leave:
        description: Channel Leave Command
    '1':
        description: Channel Command
    '2':
        description: Channel Command
    '3':
        description: Channel Command
    '4':
        description: Channel Command
    '5':
        description: Channel Command
    '6':
        description: Channel Command
    '7':
        description: Channel Command
    '8':
        description: Channel Command
    '9':
        description: Channel Command
permissions:
    elchat.*:
        description: Gives access to all ElChat commands
        childrens:
            elchat.reload: true
            elchat.channel.*: true
    elchat.channel.*:
        description: Gives access to all ElChat Channel commands
        childrens:
            elchat.channel.join: true
            elchat.channel.leave: true
            elchat.channel.create: true
            elchat.channel.list: true
            elchat.channel.ban: true
            elchat.channel.unban: true
            elchat.channel.moderator: true
            elchat.channel.unmoderator: true
            elchat.channel.moderation: true
    elchat.channel.join:
        description: Allows you to join Channel
        default: true
    elchat.channel.leave:
        description: Allows you to leave Channel
        default: true
    elchat.channel.create:
        description: Allows you to create Channel
        default: true
    elchat.channel.list:
        descripton: Allows you to list Channel
        default: true
    elchat.channel.who:
        description: Allows you to list channel users
        default: true
    elchat.channel.set:
        description: Allows you to modify channel property.
        default: true
    elchat.channel.set.autojoin:
        description: Allows you to modify autojoin property.
        default: op
    elchat.channel.set.title:
        description: Allows you to modify title property.
        default: true
    elchat.channel.set.announce:
        description: Allows you to modify announce property.
        default: true
    elchat.channel.set.forward-announce:
        description: Allows you to modify forward-announce property.
        default: op
    elchat.channel.set.roma-to-hira:
        description: Allows you to modify roma-to-hira property.
        default: true
    elchat.channel.set.password:
        description: Allows you to modify password property.
        default: true
    elchat.channel.ban:
        description: Allows you to ban channel user
        default: true
    elchat.channel.unban:
        description: Allows you to unban channel user
        default: true
    elchat.channel.moderation:
        description: Allows you to moderation Channel
        default: true
    elchat.channel.moderator:
        description: Allows you to moderator command
        default: true
    elchat.channel.unmoderator:
        description: Allows you to unmoderator command
        default: true


