global:
  message-format: '{channel} : {prefix}<{player}>{suffix}&f {message}'
  channel-format: '[{channelno}{channel}] {message}'
  roma-to-hira-format: '{message} &f({converted})'
irc:
  default-say: false
  networks:
    ircnet:
      enabled: false
      host: irc.ircnet.ne.jp
      port: 6667
      nick: ElChat
      charset: UTF-8
      channels:
        '#arle-puyon':
            title: '&9IRC&f'
            forwards: [ global, dynmap ]
            game-announce: true
            irc-announce: true
            relay-announce: false

