global:
  message-format: '[%channel] [%prefix%player%suffix&f] %message'
  join-format: '[%channel] %player joined channel.'
  quit-format: '[%channel] %player left channel.'
irc:
  networks:

