name: ElChat
main: jp.commun.minecraft.elchat.ElChatPlugin
version: 0.1.0
commands:
    elchat:
        description: ElChat Command
    channel:
        description: Channel Command
    ch:
        description: Channel Command
    '1':
        description: Channel Command
    '2':
        description: Channel Command
    '3':
        description: Channel Command
    '4':
        description: Channel Command
    '5':
        description: Channel Command
    '6':
        description: Channel Command
    '7':
        description: Channel Command
    '8':
        description: Channel Command
    '9':
        description: Channel Command
